### PR TITLE
Implement weight based bootstrapping for model

### LINKED ISSUE #8: Implementation of weight bootstrapping
Hello,

first of all: This is a great package!

Now to my question: Why is the only method of Bayesian bootstrapping resampling? Many sklearn regressor implement the weight keyword in the `fit` function and therefore could use Bayesian bootstrapping with weights instead of resampling. This approach should be much faster and less resource hungry, since only the size of the original training data matters.

Also I'm interested in implementing such a feature :)

Greetings!

### PR DESCRIPTION
**Pull request by JulianWgs**
This uses the sample_weights keywords of the `fit` function to make an bayesian bootstrap. This is more accurate and more performant than doing a resampling approach.

close #8

### CODE REVIEW

**Comment by JulianWgs** [comment]
There is still work in progress like writing tests, but I wanted to give you a chance to look at the implementation beforehand. Also I want to remark that this approach doesn't only work for regressions but also classification, etc. So I think functions like bayesian_bootstrap_regression should be renamed. Do you have anything in mind?

**Comment by JulianWgs** [comment]
Several things:

1. Underscores in module names are not PEP8.
2. Use an `__init__.py` to directly import things from a module. (bayesian_bootstrapping.mean instead of bayesian_bootstrapping.bootstrapping.mean)
3. The code largely doesnt conform to PEP8 convention. Pylint gives a 5.00 out of10.
4. Tests should deterministically.
5. Pytest should be used instead of unittest. Pytest is much more flexible.
6. Tests, which are being run by travis should should show up in this pull request.

**Comment by lmc2179** [comment]
Sorry, my availability is a little limited right now with...well, you probably know, things are a little crazy everywhere right now. Thanks for your contribution, and for writing the tests - I'll review all the code once more to see where I can improve the naming, and will take your suggestion. I'll also package up a new release and get it on conda one of these days.

Thank you again!

**Comment by JulianWgs** [comment]
Thank you!

Be safe! Right now there are more important things in life than a Github project. If I can help you in any way, just reach out. I wish you all the best.

Take care :)

**Pull request merged**
