### PR TITLE
Updates 20220125

### LINKED ISSUE #14: Use np.quantile function for central credible interval
[np.quantile](https://numpy.org/devdocs/reference/generated/numpy.quantile.html) offers the same functionality, but also interpolate between samples.

https://github.com/lmc2179/bayesian_bootstrap/blob/529758efd7a4993b3b446e9681934cb1ab50fb53/bayesian_bootstrap/bootstrap.py#L227-L238

### PR DESCRIPTION
**Pull request by genos**
Greetings!

This is a bit of a big PR, sorry about that, but I've tried to keep the commits mostly self-contained:

- 10bc19f bumps the version a little bit & drops Python 2
- de3fedb adds a `.gitignore` so that we don't pick up, say, virtual environment files
- 0b7681a puts lower bounds on the dependencies in `requirements.txt`
- 99d31ed removes a reference to Python 2 since it's no longer supported by the Python foundation
- cba4cde removes dependence on `pandas` since it's not used anywhere
- 85237d9 reads `requirements.txt` into the `install_requires` field of `setup.py`
- 70fa631f closes #14 by using `np.quantile` instead of by-hand sorting & list creation. It also updates the tests accordingly, including using a seeded pseudorandom number generator throughout to avoid flaky tests
- Given all the above, 5943ce6 bumps the version even more

I'd like to also push again for publishing a new version on PyPI, as the `1.0.5` version that's up is out of date.

Thanks as ever for this really cool and useful project!

### CODE REVIEW

**Comment by genos** [comment]
👋  Pinging on this

**Comment by lmc2179** [comment]
Hi! Thank you for all the work you've put in here - I'll finalize this and bump the version this week (it has, quite honestly, been so long that I've forgotten how, haha). Thank you for putting up with my slowness!

**Comment by genos** [comment]
Not at all! Thanks for putting up with my annoying PRs 😆

**Comment by genos** [comment]
Just noticed a typo in one of my comments; apologies!

**Comment by genos** [comment]
Hi! Any movement on this?

**Comment by lmc2179** [comment]
Just merged - will cut a new release on PyPI shortly. Thank you, once again, for your contribution! It's been a bit of a difficult time for me, and it's likely that this project would not have gotten these improvements without you. I really appreciate it!

**Comment by genos** [comment]
Thank you for your awesome project and kind words!

**Pull request merged**
