### PR TITLE
Simplify Importing

### PR DESCRIPTION
**Pull request by genos**
Hello again! Thanks as ever for this very valuable tool, it's been great.

In using it, I've found myself (a _very_ lazy user 😆) wanting to simplify the importing structure a bit; hence, this PR.

I've moved `bootstrap.py` to `__init__.py`; this means that rather than requiring `from bayesian_bootstrap.bootstrap import X` for imports we only need to say `from bayesian_bootstrap import X`, simplifying things a little. I've updated the README, demos, and tests to reflect this change. I also tweaked the delta value for one test, as it failed
intermittently with randomized data.

### CODE REVIEW

**Comment by genos** [comment]
Just checking in; any thoughts on this PR?

**Comment by genos** [comment]
Happy new year! Any update on whether I should scrap this PR or not?

**Comment by lmc2179** [comment]
Hi! Thanks for your patience...lots going on these days. I'll test this and get back to you!

**Comment by lmc2179** [comment]
Looks good. Thank you!

**Comment by genos** [comment]
Great, thanks! Might I further presume upon your generosity and ask you to bump the version and update PyPI? 🙏

**Pull request merged**
